branch-defaults:
  default:
    environment: ravin-project
    group_suffix: null
  master:
    environment: ravin-project
global:
  application_name: ravin-project
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 18
  default_region: sa-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
